name: Release api Package

on:
    workflow_call:
        inputs:
            VERSION_TYPE:
                required: true
                type: string
            NPM_PUBLISH:
                required: true
                type: string

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  registry-url: 'https://registry.npmjs.org'

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Update version
              working-directory: ./packages/api
              run: |
                  git pull origin main
                  pnpm version ${{ inputs.VERSION_TYPE }} --no-git-tag-version

            - name: Commit changes
              run: |
                  git add .
                  git commit -m "chore(release): update api package version [skip ci]"
                  git push origin main

            - name: Build package
              run: pnpm run build:api

            - name: Publish package
              run: pnpm --filter @scope/api publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ inputs.NPM_PUBLISH }}
